from mash_cv import cv as _cv_module
from mash_cv.cv import (
    DEFAULT_COMMAND_CARD_SLOTS,
    DEFAULT_NP_GAUGE_DIGIT_SLOT_REGIONS,
    DEFAULT_NP_GAUGE_DIGIT_REGIONS,
    DEFAULT_NP_CARD_SLOTS,
    FACE_CROP_REL_H,
    BATTLE_DIGIT_SCORE_MARGIN,
    _classify_suit_in_slot,
    _crop_template,
    _detect_screen,
    _ensure_icon_color_sigs,
    _face_cache,
    _face_search_bbox,
    _find_command_cards,
    _find_element,
    _find_element_by_name,
    _find_enhancement_servant_grid,
    _find_item_grid,
    _find_noble_phantasms,
    _get_template,
    _icon_color_sig,
    _identify_servant_in_slot,
    _load_config,
    _load_templates,
    _match_template_region,
    _ocr_region,
    _probe_skill_use_dialog,
    _read_battle_scene,
    _read_bond_level_up,
    _read_level_digits,
    _read_region_luma,
    _reply,
    _resize_template,
    _respond,
    _slot_to_pixels,
    _suit_sample_bbox,
    main,
    template_masks,
    templates,
)


def _set_config(new_config: dict) -> None:
    """Replace the module-level config (used by tests)."""
    _cv_module.config = new_config


def _get_config() -> dict:
    return _cv_module.config


__all__ = [
    "DEFAULT_COMMAND_CARD_SLOTS",
    "DEFAULT_NP_GAUGE_DIGIT_SLOT_REGIONS",
    "DEFAULT_NP_GAUGE_DIGIT_REGIONS",
    "DEFAULT_NP_CARD_SLOTS",
    "FACE_CROP_REL_H",
    "BATTLE_DIGIT_SCORE_MARGIN",
    "_classify_suit_in_slot",
    "_crop_template",
    "_detect_screen",
    "_ensure_icon_color_sigs",
    "_face_cache",
    "_face_search_bbox",
    "_find_command_cards",
    "_find_element",
    "_find_element_by_name",
    "_find_enhancement_servant_grid",
    "_find_item_grid",
    "_find_noble_phantasms",
    "_get_config",
    "_get_template",
    "_icon_color_sig",
    "_identify_servant_in_slot",
    "_load_config",
    "_load_templates",
    "_match_template_region",
    "_ocr_region",
    "_probe_skill_use_dialog",
    "_read_battle_scene",
    "_read_bond_level_up",
    "_read_level_digits",
    "_read_region_luma",
    "_reply",
    "_resize_template",
    "_respond",
    "_set_config",
    "_slot_to_pixels",
    "_suit_sample_bbox",
    "main",
    "template_masks",
    "templates",
]
